services:

  # FTC RestaurantHistory API
  app:
    env_file:
      .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ftc_restaurant_history_api
    ports:
      - "8085:8085"
    depends_on:
      - ftc_restaurant_history_database
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ftc_restaurant_history_database:5433/ftc_restaurant_history_database
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - ftc_restaurant_history_database_net
    profiles: ["docker"]


  # DATABASE
  ftc_restaurant_history_database:
    env_file:
      .env
    container_name: ftc_restaurant_history_database
    image: postgres:17.4
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ftc_restaurant_history_database
    networks:
      - ftc_restaurant_history_database_net
    volumes:
      - ftc_restaurant_history_database:/var/lib/postgresql
      - ftc_restaurant_history_database_data:/var/lib/postgresql/data

networks:
  ftc_restaurant_history_database_net:

volumes:
  ftc_restaurant_history_database:
  ftc_restaurant_history_database_data: