# SERVER CONFIG
server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8087
  servlet:
    context-path: /restaurant-history
    encoding:
      charset: UTF-8
      enabled: true

# SPRING CONFIG
spring:
  application:
    name: FTC.RestaurantHistory.API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5453/ftc_restaurant_history_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9093
    topic:
      name:
        producer: dto
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      FAIL_ON_EMPTY_BEANS: false
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
    time-zone: America/Sao_Paulo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  devtools:
    livereload:
      enabled: false
  mandatory-file-encoding: UTF-8
  flyway:
    schemas: public
    table: t_flyway_schema_history
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: user
logging:
  level:
    org:
      flywaydb: debug
      springframework.web: DEBUG
      org.hibernate: ERROR